### ISSUE TITLE
Add support for info panels

### ISSUE THREAD

**Issue by xens** [kovetskiy/mark#48]
would be awesome if we could use annotations inside the markdown files to add Confluence "info panels".

![image](https://user-images.githubusercontent.com/1699826/102323980-7d45f580-3f81-11eb-98d1-d5d7960a307c.png)

**Comment by kovetskiy** [comment]
This is already possible using macros, isn't it?

**Comment by GrantAdkins** [comment]
Same as my issue: https://github.com/kovetskiy/mark/issues/40

**Comment by xens** [comment]
> This is already possible using macros, isn't it?

As I understand what is supported is Status-macro https://confluence.atlassian.com/conf59/status-macro-792499207.html but not info panels, or am I missing something ?

**Comment by GrantAdkins** [comment]
Definitely not the status macro. It's the info/warning/error/etc panels macro you'd want for the new Confluence editor:

![image](https://user-images.githubusercontent.com/2025241/102343822-c3817000-3fe6-11eb-94f1-b30bba8f7e98.png)

**Comment by seletskiy** [comment]
This should be possible by using [Info, Tip, Note and Warning Macros](https://confluence.atlassian.com/doc/info-tip-note-and-warning-macros-51872369.html) and by using more generic [Panel Macro](https://confluence.atlassian.com/doc/panel-macro-51872380.html).
Also, see the (probably most comprehensive) [list of other macros](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) available in Confluence.

By the way, to avoid copy-pasting macro code in every `md` file it is possible to put it into template file and then use `<!-- Macro` definition, like this:
```markdown
<!-- Macro: panel:info
     Template: macros/panel.tpl
     Title: Translation
     Body: This documentation is available in 42 other languages.
-->
```

**macros/panel.tpl**:

```markdown
{info:title={{ .Title }}|icon=false}
{{ .Body }}
{info}
```

**Comment by xens** [comment]
I'm probably doing something wrong but with your example above @seletskiy I don't have anything rendered in Confluence only the same data as in the `macros/panel.tpl` file

![image](https://user-images.githubusercontent.com/1699826/102415295-3a733480-3ff8-11eb-8f3e-0057b5723e1c.png)

**Comment by seletskiy** [comment]
@xens No, you did everything as written.

In fact, I was wrong and macros should be defined in [HTML-like style](https://confluence.atlassian.com/conf59/panel-macro-792499179.html) (see "Storage format example"), e.g. by using `<ac:structured-macro ac:name="panel">` tag.

Unfortunately, it is not working anymore (at least in Cloud, however, it might still work in some self-hosted versions), and you will get error trying this:
> Content body cannot be converted to new editor format.

Fact is that Atlassian previously used the so-called "Storage format" in order to store article text, and it seems that Atlassian is changing their internal representation, so while some macros still work, more will be most likely to be disabled in the future.

By peeking into inspector in the browser it looks like they are using the format called `atlas_doc_format` (**undocumented**) and it differs from what mark is sending right now:

![image](https://user-images.githubusercontent.com/674812/102500720-ac498d80-408d-11eb-9535-ce64b5f3dd37.png)

I guess that `mark` should be adapted to the new internal representation format in order to support Macros in the future (or maybe to work at all).

**Comment by sheldonhull** [comment]
I looked into trying to accomplish this with [asciidoc-confluence](https://github.com/asciidoctor/asciidoctor-confluence) in the past when I used it, but it was very complex. From what I can tell in reviewing this, considering I'm more versed with Go, it's setup to make this possible.

Would you consider a contributor guide to adding new macros?

Forgive the length, but since it's on topic of asking for a new feature, I wrote my progress here on what I looked at so it's from a set of fresh eyes. Maybe with a little bit of contributing guidance it would be easy to extend this out.

## The Current Template Structure & Location

1. You are using the storage format, ie the confluence specific xhtml standards documented [here](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) [macro-callout](https://confluence.atlassian.com/conf59/info-tip-note-and-warning-macros-792499127.html)
1. The macro logic is contained here: [macro.go](https://github.com/kovetskiy/mark/blob/master/pkg/mark/macro/macro.go)
1. If we contributed a new macro it would be added to the string map here:

https://github.com/kovetskiy/mark/blob/bcf2acb39fd38c99f6c150f71286618f57a9fda5/pkg/mark/stdlib/stdlib.go#L91

with something like:

```go
`ac:callout`: text(
			`<ac:structured-macro ac:name="{{ .Type }}">`,
			`<ac:parameter ac:name="icon">false</ac:parameter>`,
			`<ac:parameter ac:name="title">{{ .CalloutTitle }}</ac:parameter>`,
			`<ac:rich-text-body>`,
		    `<p>`,
		    `{{ .Message | converttohtml }}`, <------- pseduocode from my hugo style experience
		    `</p>`,
		    `</ac:rich-text-body>`,
			`</ac:structured-macro>`,
),
```

1. This would use the text template I provide in my doc like this:

```text
<!-- Macro: info|warning|note etc
     Template: ac:callout
	 CalloutTitle: My Important Callout Title
     Message: Message-->
```

### Quick Side Note On Text Templates

Personally, I'm a big fan of hugo's shortcode formatting as it makes the text block very clear, but I'm not certain this applies as I think you are using this html markup to accomplish the parsing, correct? 

An example of rendering with hugo allows template syntax... very top of the page I have a "Any Questions Section" [link](https://www.sheldonhull.com/docs/powershell/) and the [source](https://github.com/sheldonhull/sheldonhull.hugo/blob/master/content/docs/powershell.md#L15-L19) using a shortcode: 

https://github.com/sheldonhull/sheldonhull.hugo/blob/4ea94df87375e9bc82534e2af4071f9c8d71f19d/layouts/shortcodes/premonition.html#L1-L12

Not sure if it would be easy to leverage this to parse the objects later, but figured I'd mention since it's a tried and true pattern for one of the most populate static site generators out there.

## wrap up

It's a bit long, but figured I'd capture my review over the last few minutes, as adding macros and features all by one person is hard to scale. Would love to know how to better contribute!

**Comment by sheldonhull** [comment]
As one addendum, it might be a much bigger feature depending on code layout, but IF in alignment and want to have contributions by people more easily made, consider the note about shortcodes like hugo does.

This is very easily for scaling out for contributions as very little source code changes required for new macros to be added, just a new shortcode (linked above). 

I'm guessing it's a bigger change to how this project is structured, but worth mentioning as it's what makes hugo so flexible for generating sites.

**Comment by rofafor** [comment]
This is pretty much the same as done in https://github.com/kovetskiy/mark/pull/77

**Comment by kovetskiy** [comment]
Version 5.5 which contains `ac:box` macro by @rofafor is released. 

Readme: https://github.com/kovetskiy/mark#insert-colored-text-box
Release: https://github.com/kovetskiy/mark/releases/tag/5.5
